name: codecheck-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - nbconvert>=6
  - notebook>=6
  - jupyterlab
  - matplotlib>=3.4
  - pandas>=1.3
  - tabulate
  - pyyaml
  - pytest>=7.0
  - pytest-cov
  - requests
 
